<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /var/www/html/app/Controllers/../../views/indicadores/seguros/servicios.latte */
final class Template_47b34635c8 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="min-h-screen bg-base-200 p-4 sm:p-6 lg:p-8">
    <div class="max-w-7xl mx-auto">
        <div class="mb-8">
            <h1 class="text-4xl font-bold text-base-content mb-2">
                <i class="fas fa-shield-alt mr-3"></i>Servicios de Seguros
            </h1>
            <p class="text-base-content/70">Gestiona los servicios y sus costos asociados</p>
        </div>

        <div class="card bg-base-100 shadow-xl mb-8">
            <div class="card-body">
                <h2 class="card-title text-2xl mb-6">
                    <i class="fas fa-plus-circle mr-2"></i>
                    ';
		if (isset($currentService) && $currentService->id) /* pos 17:21 */ {
			echo 'Editar Servicio';
		} else /* pos 17:86 */ {
			echo 'Nuevo Servicio';
		}
		echo '
                </h2>

                <form id="servicioForm" method="';
		if (isset($currentService) && $currentService->id) /* pos 20:49 */ {
			echo 'PUT';
		} else /* pos 20:102 */ {
			echo 'POST';
		}
		echo '"
                    action="api/seguros/servicios">
                    <input type="hidden" name="csrf_token" id="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 22:84 */;
		echo '>
                    <input type="hidden" name="id" id="id"';
		echo LR\HtmlHelpers::formatAttribute(' value', $currentService->id ?? '') /* pos 23:68 */;
		echo '>

                    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
                        <div class="form-control">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-tag mr-2"></i>Nombre del Servicio
                                </span>
                            </label>
                            <input type="text" name="nombre" id="nombre"';
		echo LR\HtmlHelpers::formatAttribute(' value', $currentService->nombre ?? '') /* pos 33:82 */;
		echo '
                                placeholder="Ej: Seguro contra incendios" required
                                class="input input-bordered w-full focus:input-primary">
                        </div>

                        <div class="form-control">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-align-left mr-2"></i>Descripción
                                </span>
                            </label>
                            <input type="text" name="descripcion" id="descripcion"';
		echo LR\HtmlHelpers::formatAttribute('
                                value', $currentService->descripcion ?? '') /* pos 46:41 */;
		echo ' placeholder="Descripción del servicio"
                                required class="input input-bordered w-full focus:input-primary">
                        </div>

                        <div class="form-control">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-dollar-sign mr-2"></i>Costo
                                </span>
                            </label>
                            <input type="number" name="costo" id="costo"';
		echo LR\HtmlHelpers::formatAttribute(' value', $currentService->costo ?? '') /* pos 57:82 */;
		echo '
                                step="0.01" placeholder="0.00" required
                                class="input input-bordered w-full focus:input-primary">
                        </div>

                        <div class="form-control">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-calculator mr-2"></i>Cuenta Contable
                                </span>
                            </label>
                            <select name="cuenta_contable" id="cuenta_contable" required
                                class="select select-bordered w-full focus:select-primary">
                                <option value="" selected disabled>Seleccione una cuenta</option>
';
		$currentGroupOpen = false /* pos 72:33 */;
		if (count($nomenclaturaContable) > 0) /* pos 73:33 */ {
			foreach ($nomenclaturaContable as $cuenta) /* pos 74:33 */ {
				$level = (int) (strlen($cuenta->ccodcta) / 2) /* pos 75:33 */;
				$indent = str_repeat('&nbsp;', max(0, $level - 1) * 4) /* pos 76:33 */;
				echo "\n";
				if (($cuenta->tipo ?? '') === 'R') /* pos 78:33 */ {
					echo '                                ';
					if ($currentGroupOpen) /* pos 79:33 */ {
						echo '</optgroup>';
					}
					echo '
                                <optgroup label="';
					echo LR\HtmlHelpers::escapeQuotes($indent) /* pos 80:50 */;
					echo LR\HtmlHelpers::escapeAttr($cuenta->cdescrip) /* pos 80:68 */;
					echo '">
';
					$currentGroupOpen = true /* pos 81:37 */;
				} else /* pos 82:37 */ {
					$selected = isset($currentService->id_nomenclatura) && (int) $currentService->id_nomenclatura === (int) $cuenta->id ? ' selected' : '' /* pos 83:37 */;
					echo '                                    <option';
					echo LR\HtmlHelpers::formatAttribute(' value', $cuenta->id) /* pos 85:53 */;
					echo ' ';
					echo LR\HtmlHelpers::escapeTag($selected) /* pos 85:67 */;
					echo '>
                                        ';
					echo $indent /* pos 86:41 */;
					echo LR\HtmlHelpers::escapeText($cuenta->ccodcta) /* pos 86:59 */;
					echo ' - ';
					echo LR\HtmlHelpers::escapeText($cuenta->cdescrip) /* pos 86:80 */;
					echo '
                                    </option>
';
				}

			}

			if ($currentGroupOpen) /* pos 90:37 */ {
				echo '                                </optgroup>';
			}
			echo "\n";
		} else /* pos 92:33 */ {
			echo '                                <option value="">No hay cuentas contables disponibles</option>
';
		}
		echo '                            </select>
                        </div>

                        <div class="form-control">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-dollar-sign mr-2"></i>Edad Mínima
                                </span>
                            </label>
                            <input type="number" name="edad_minima" id="edad_minima"';
		echo LR\HtmlHelpers::formatAttribute('
                                value', $currentService->edad_minima ?? '') /* pos 106:41 */;
		echo ' step="1" placeholder=""
                                class="input input-bordered w-full focus:input-primary">
                        </div>
                        <div class="form-control">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-dollar-sign mr-2"></i>Edad Máxima
                                </span>
                            </label>
                            <input type="number" name="edad_maxima" id="edad_maxima"';
		echo LR\HtmlHelpers::formatAttribute('
                                value', $currentService->edad_maxima ?? '') /* pos 117:41 */;
		echo ' step="1" placeholder=""
                                class="input input-bordered w-full focus:input-primary">
                        </div>
                        <div class="form-control lg:col-span-2">
                            <label class="label">
                                <span class="label-text font-semibold">
                                    <i class="fas fa-align-left mr-2"></i>Notas
                                </span>
                            </label>
                            <input type="text" name="notas" id="notas"';
		echo LR\HtmlHelpers::formatAttribute(' value', $currentService->notas ?? '') /* pos 127:80 */;
		echo '
                                placeholder="Notas adicionales" class="input input-bordered w-full focus:input-primary">
                        </div>
                    </div>

                    <div class="card-actions justify-end mt-8">
                        <button type="button" onclick="submitForm(\'#servicioForm\', {
                            confirmMessage: \'¿Está seguro de que desea guardar este servicio?\'
                            });" class="btn btn-primary gap-2">
                            <i class="fas fa-save"></i>
                            ';
		if (isset($currentService) && $currentService->id) /* pos 137:29 */ {
			echo 'Actualizar Servicio';
		} else /* pos 137:98 */ {
			echo 'Guardar
                            Servicio';
		}
		echo '
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card bg-base-100 shadow-xl">
            <div class="card-body">
                <h2 class="card-title text-2xl mb-6">
                    <i class="fas fa-list mr-2"></i>Listado de Servicios
                </h2>

';
		if (count($services) > 0) /* pos 152:17 */ {
			echo '                <div class="overflow-x-auto">
                    <table class="table table-zebra w-full" id="tableServices">
                        <thead>
                            <tr>
                                <th class="bg-primary text-primary-content">#</th>
                                <th class="bg-primary text-primary-content">
                                    <i class="fas fa-tag mr-2"></i>Nombre
                                </th>
                                <th class="bg-primary text-primary-content">
                                    <i class="fas fa-align-left mr-2"></i>Descripción
                                </th>
                                <th class="bg-primary text-primary-content">
                                    <i class="fas fa-dollar-sign mr-2"></i>Costo
                                </th>
                                <th class="bg-primary text-primary-content text-center">
                                    <i class="fas fa-cog mr-2"></i>Acciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>
';
			foreach ($services as $key => $service) /* pos 173:29 */ {
				echo '                            <tr class="hover">
                                <td class="font-semibold">';
				echo LR\HtmlHelpers::escapeText($key + 1) /* pos 175:59 */;
				echo '</td>
                                <td class="font-medium">';
				echo LR\HtmlHelpers::escapeText($service->nombre) /* pos 176:57 */;
				echo '</td>
                                <td>';
				echo LR\HtmlHelpers::escapeText($service->descripcion) /* pos 177:37 */;
				echo '</td>
                                <td>
                                    <div class="badge badge-success gap-2">
                                        <i class="fas fa-dollar-sign"></i>
                                        ';
				echo LR\HtmlHelpers::escapeText($service->costo) /* pos 181:41 */;
				echo '
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="join">
                                        <button class="btn btn-sm btn-info join-item gap-2" onclick="loadModuleView(\'#cuadro\', {
                                                route: \'api/seguros/servicios/edit/';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($service['id'])) /* pos 187:84 */;
				echo '\'
                                            });">
                                            <i class="fas fa-edit"></i>
                                            Editar
                                        </button>
                                        <button class="btn btn-sm btn-error join-item gap-2" onclick="sendRequest({
                                            url: \'api/seguros/servicios/';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($service->id)) /* pos 193:73 */;
				echo '\', 
                                            method: \'DELETE\', 
                                            confirmMessage: \'¿Está seguro de eliminar el servicio ';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($service->nombre)) /* pos 195:101 */;
				echo '?\'
                                            });">
                                            <i class="fas fa-trash"></i>
                                            Eliminar
                                        </button>
                                    </div>
                                </td>
                            </tr>
';

			}

			echo '                        </tbody>
                    </table>
                </div>
';
		} else /* pos 207:17 */ {
			echo '                <div class="hero min-h-[300px] bg-base-200 rounded-lg">
                    <div class="hero-content text-center">
                        <div class="max-w-md">
                            <div class="text-6xl mb-4">
                                <i class="fas fa-inbox text-base-content/20"></i>
                            </div>
                            <h3 class="text-2xl font-bold text-base-content">
                                No hay servicios registrados
                            </h3>
                            <p class="py-6 text-base-content/70">
                                Comience agregando un nuevo servicio utilizando el formulario anterior.
                            </p>
                        </div>
                    </div>
                </div>
';
		}
		echo '            </div>
        </div>
    </div>

    <script>
        // Destruir instancia previa de Select2 si existe
        if ($(\'#cuenta_contable\').data(\'select2\')) {
            $(\'#cuenta_contable\').select2(\'destroy\');
        }

        // Inicializar Select2
        initSelect2(\'#cuenta_contable\', {
            dropdownParent: $(\'body\'),
            placeholder: \'Seleccione una cuenta contable\'
        });

        // Establecer el valor si existe (para modo edición)
';
		if (isset($currentService->id_nomenclatura) && $currentService->id_nomenclatura) /* pos 241:9 */ {
			echo '        $(\'#cuenta_contable\').val(';
			echo LR\Helpers::escapeJs($currentService->id_nomenclatura) /* pos 242:35 */;
			echo ').trigger(\'change\');
';
		}
		echo '
        startValidationGeneric(\'#servicioForm\');
        convert_table_to_datatable(\'tableServices\');
    </script>
</div>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['cuenta' => '74', 'key' => '173', 'service' => '173'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
