<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /var/www/html/app/Controllers/../../views/indicadores/seguros/renovaciones.latte */
final class Template_fd55d64073 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="p-6 max-w-7xl mx-auto">
    <div class="card bg-gradient-to-br from-base-100 to-base-200 shadow-xl border border-base-300 mb-6">
        <div class="card-body">
            <div class="flex items-center justify-between mb-6">
                <div class="flex items-center gap-3">
                    <div>
                        <h2 class="card-title text-2xl">Información de la Cuenta</h2>
                        <p class="text-sm text-base-content/60">
';
		if (isset($cuenta) && isset($cuenta->id)) /* pos 10:29 */ {
			echo '                            Cuenta #';
			echo LR\HtmlHelpers::escapeText($cuenta->id) /* pos 11:37 */;
			echo "\n";
		} else /* pos 12:29 */ {
			echo '                            Sin cuenta seleccionada
';
		}
		echo '                        </p>
                    </div>
                </div>
                <div class="flex gap-2">
                    <button type="button" class="btn btn-primary btn-sm gap-2" onclick="modal_cuentas.showModal()">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"></path>
                        </svg>
                        ';
		if (isset($cuenta) && isset($cuenta->id)) /* pos 25:25 */ {
			echo 'Cambiar';
		} else /* pos 25:73 */ {
			echo 'Seleccionar';
		}
		echo ' Cuenta
                    </button>
                    <button type="button" class="btn btn-ghost btn-sm" onclick="loadModuleView(\'#cuadro\', {
                                                route: \'api/seguros/renovaciones/index\'
                                            });">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                        Cancelar
                    </button>
                </div>
            </div>

';
		if (!isset($cuenta) || !isset($cuenta->id)) /* pos 40:13 */ {
			echo '            <div class="alert alert-info shadow-lg">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    class="stroke-current shrink-0 w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <div>
                    <h3 class="font-bold">Ninguna cuenta seleccionada</h3>
                    <div class="text-xs">Use el botón "Seleccionar Cuenta" para buscar y elegir una cuenta.</div>
                </div>
            </div>
';
		} else /* pos 53:13 */ {
			echo '            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Cliente</div>
                    <div class="stat-value text-lg truncate"';
			echo LR\HtmlHelpers::formatAttribute(' title', $cuenta->cliente->short_name ?? 'N/A') /* pos 65:70 */;
			echo '>
                        ';
			echo LR\HtmlHelpers::escapeText($cuenta->cliente->short_name ?? 'N/A') /* pos 66:25 */;
			echo '
                    </div>
                    <div class="stat-desc">';
			echo LR\HtmlHelpers::escapeText($cuenta->cliente->no_identifica ?? '') /* pos 68:44 */;
			echo '</div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Servicio</div>
                    <div class="stat-value text-lg">';
			echo LR\HtmlHelpers::escapeText($cuenta->servicio->nombre ?? 'N/A') /* pos 80:53 */;
			echo '</div>
                    <div class="stat-desc">Costo: <span class="font-bold">';
			echo LR\HtmlHelpers::escapeText($cuenta->servicio->costo ?? 0) /* pos 81:75 */;
			echo '</span></div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-accent">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Fecha Inicio</div>
                    <div class="stat-value text-lg">
                        ';
			if (isset($cuenta->fecha_inicio)) /* pos 94:25 */ {
				echo LR\HtmlHelpers::escapeText(date('d/m/Y', strtotime($cuenta->fecha_inicio))) /* pos 94:58 */;
			} else /* pos 94:107 */ {
				echo 'N/A';
			}
			echo '
                    </div>
                    <div class="stat-desc">
';
			if (isset($cuenta->estado) && $cuenta->estado == 'vigente') /* pos 97:25 */ {
				echo '                        <span class="badge badge-success badge-sm">Vigente</span>
';
			} elseif (isset($cuenta->estado) && $cuenta->estado == 'cerrada') /* pos 99:25 */ {
				echo '                        <span class="badge badge-info badge-sm">Cerrada</span>
';
			} elseif (isset($cuenta->estado)) /* pos 101:25 */ {
				echo '                        <span class="badge badge-ghost badge-sm">';
				echo LR\HtmlHelpers::escapeText($cuenta->estado) /* pos 102:66 */;
				echo '</span>
';
			} else /* pos 103:25 */ {
				echo '                        <span class="badge badge-ghost badge-sm">Sin estado</span>
';
			}


			echo '                    </div>
                </div>
            </div>

';
			if (isset($cuenta->observaciones) && !empty($cuenta->observaciones)) /* pos 110:13 */ {
				echo '            <div class="mt-4 p-4 bg-base-200 rounded-lg">
                <div class="flex items-start gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-base-content/60 flex-shrink-0 mt-0.5"
                        fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path>
                    </svg>
                    <div>
                        <p class="text-xs font-semibold text-base-content/70 uppercase">Observaciones</p>
                        <p class="text-sm">';
				echo LR\HtmlHelpers::escapeText($cuenta->observaciones) /* pos 120:44 */;
				echo '</p>
                    </div>
                </div>
            </div>
';
			}
		}
		echo '        </div>
    </div>

';
		if (isset($cuenta) && isset($cuenta->renovaciones) && count($cuenta->renovaciones) > 0) /* pos 130:5 */ {
			echo '    <div class="card bg-base-100 shadow-xl border border-base-300 mb-6">
        <div class="card-body">
            <div class="flex items-center justify-between mb-6">
                <div class="flex items-center gap-3">
                    <div>
                        <h2 class="card-title text-2xl">Historial de Renovaciones</h2>
                        <p class="text-sm text-base-content/60">';
			echo LR\HtmlHelpers::escapeText(count($cuenta->renovaciones)) /* pos 137:65 */;
			echo '
                            ';
			echo LR\HtmlHelpers::escapeText(count($cuenta->renovaciones) == 1 ? 'renovación' : 'renovaciones') /* pos 138:29 */;
			echo '</p>
                    </div>
                </div>
            </div>

            <div class="overflow-x-auto">
                <table class="table table-zebra">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Número</th>
                            <th>Fecha Renovación</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Monto</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
';
			foreach ($cuenta->renovaciones as $renovacion) /* pos 157:25 */ {
				echo '                        <tr>
                            <td>';
				echo LR\HtmlHelpers::escapeText($renovacion->id) /* pos 159:33 */;
				echo '</td>
                            <td><span class="badge badge-neutral">#';
				echo LR\HtmlHelpers::escapeText($renovacion->numero) /* pos 160:68 */;
				echo '</span></td>
                            <td>';
				echo LR\HtmlHelpers::escapeText(date('d/m/Y', strtotime($renovacion->fecha))) /* pos 161:33 */;
				echo '</td>
                            <td>';
				echo LR\HtmlHelpers::escapeText(date('d/m/Y', strtotime($renovacion->fecha_inicio))) /* pos 162:33 */;
				echo '</td>
                            <td>';
				echo LR\HtmlHelpers::escapeText(date('d/m/Y', strtotime($renovacion->fecha_fin))) /* pos 163:33 */;
				echo '</td>
                            <td><span class="font-bold text-primary">';
				echo LR\HtmlHelpers::escapeText($renovacion->monto) /* pos 164:70 */;
				echo '</span></td>
                            <td>
                                <button class="btn btn-xs btn-ghost gap-1" onclick="reporteManager.generarReporteDirect(
                                        \'seguros/comprobante-renovacion\',
                                        { 
                                            id: ';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($renovacion->id)) /* pos 169:49 */;
				echo ',
                                            csrf_token: ';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($csrf_token)) /* pos 170:57 */;
				echo '
                                        },
                                        { tipo: \'show\' }
                                    );">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                                    </svg>
                                    Comprobante
                                </button>
                                <button class="btn btn-xs btn-ghost gap-1" onclick="reporteManager.generarReporteDirect(
                                        \'seguros/contrato-renovacion\',
                                        { 
                                            id: ';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($renovacion->id)) /* pos 186:49 */;
				echo ',
                                            csrf_token: ';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($csrf_token)) /* pos 187:57 */;
				echo '
                                        },
                                        { tipo: \'show\' }
                                    );">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                                    </svg>
                                    Contrato
                                </button>
                            </td>
                        </tr>
';

			}

			echo '                    </tbody>
                </table>
            </div>
        </div>
    </div>
';
		}
		echo "\n";
		if (isset($cuenta) && isset($cuenta->id)) /* pos 209:5 */ {
			echo '    <div class="card bg-base-100 shadow-xl border border-success/30 mb-6" id="renovacionForm"
        x-data="{ formaPago: \'efectivo\' }" data-action="api/seguros/renovaciones" data-method="POST">
        <div class="card-body">
            <div class="flex items-center gap-3 mb-6">
                <div>
                    <h2 class="card-title text-2xl">Nueva Renovación</h2>
                    <p class="text-sm text-base-content/60">Registre una nueva renovación para esta cuenta</p>
                </div>
            </div>

            <input type="hidden" name="csrf_token"';
			echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 220:60 */;
			echo '>
            <input type="hidden" name="id_cuenta"';
			echo LR\HtmlHelpers::formatAttribute(' value', $cuenta->id ?? '') /* pos 221:59 */;
			echo '>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div class="form-control">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                            </svg>
                            Número de documento
                        </span>
                    </label>
                    <input required type="text" id="numdoc" name="numdoc" class="input input-bordered input-primary"
                        placeholder="Ej: 1xx" data-label="Número de documento" />
                </div>

                <div class="form-control">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                            </svg>
                            Fecha Renovación
                        </span>
                    </label>
                    <input type="date" id="fecha" name="fecha" class="input input-bordered input-primary"';
			echo LR\HtmlHelpers::formatAttribute('
                        value', date('Y-m-d')) /* pos 251:33 */;
			echo ' required data-label="Fecha Renovación" />
                </div>

                <div class="form-control">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            Monto
                        </span>
                    </label>
                    <input type="number" step="0.01" id="monto" name="monto" class="input input-bordered input-primary"
                        placeholder="0.00"';
			echo LR\HtmlHelpers::formatAttribute(' value', $cuenta->servicio->costo ?? '') /* pos 266:52 */;
			echo ' required data-label="Monto"
                        min="0" />
                </div>

                <div class="form-control">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
                            </svg>
                            Fecha Inicio
                        </span>
                    </label>
                    <input type="date" id="fecha_inicio" name="fecha_inicio" class="input input-bordered input-primary"';
			echo LR\HtmlHelpers::formatAttribute('
                        value', date('Y-m-d')) /* pos 282:33 */;
			echo ' required data-label="Fecha Inicio" />
                </div>

                <div class="form-control">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                            </svg>
                            Fecha Fin
                        </span>
                    </label>
                    <input type="date" id="fecha_fin" name="fecha_fin" class="input input-bordered input-primary"
                        required data-label="Fecha Fin" />
                </div>
            </div>

            <div class="divider"></div>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div class="form-control">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                            </svg>
                            Forma de pago
                        </span>
                    </label>
                    <select class="select" id="forma_pago" name="forma_pago" required x-model="formaPago"
                        data-label="Forma de pago">
                        <option value="" disabled selected>Seleccione</option>
                        <option value="efectivo">Efectivo</option>
                        <option value="banco">Boleta de banco</option>
                    </select>
                </div>

                <div class="form-control" x-show="formaPago === \'banco\'" x-cloak>
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                            </svg>
                            Cuentas Bancarias
                        </span>
                    </label>
                    <select class="select" id="cuenta_banco" name="cuenta_banco" :required="formaPago === \'banco\'"
                        data-label="Cuenta Bancaria">
                        <option value="" disabled selected>Seleccione</option>
';
			foreach ($cuentasBancos as $cuentaBanco) /* pos 336:25 */ {
				echo '                        <option';
				echo LR\HtmlHelpers::formatAttribute(' value', $cuentaBanco->id) /* pos 337:41 */;
				echo '>';
				echo LR\HtmlHelpers::escapeText($cuentaBanco->banco->nombre ?? 'N/A') /* pos 337:60 */;
				echo ' -
                            ';
				echo LR\HtmlHelpers::escapeText($cuentaBanco->numcuenta ?? 'N/A') /* pos 338:29 */;
				echo '</option>
';

			}

			echo '                    </select>
                </div>

                <div class="form-control" x-show="formaPago === \'banco\'" x-cloak>
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                            </svg>
                            Número de boleta
                        </span>
                    </label>
                    <input type="text" id="numero_boleta" name="numero_boleta"
                        class="input input-bordered input-primary" placeholder="Ej: 1xx"
                        :required="formaPago === \'banco\'" data-label="Número de boleta" />
                </div>

                <div class="form-control" x-show="formaPago === \'banco\'" x-cloak>
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                            </svg>
                            Fecha boleta
                        </span>
                    </label>
                    <input type="date" id="fecha_boleta" name="fecha_boleta" class="input input-bordered input-primary"';
			echo LR\HtmlHelpers::formatAttribute('
                        value', date('Y-m-d')) /* pos 371:33 */;
			echo ' :required="formaPago === \'banco\'" data-label="Fecha de boleta" />
                </div>
            </div>


            <div class="divider"></div>

            <div class="flex gap-3 justify-end">
                <button type="button" class="btn btn-ghost gap-2" onclick="loadModuleView(\'#cuadro\', {
                                                route: \'api/seguros/cuentas/index\'
                                            });">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                    Cancelar
                </button>
                <button type="button" class="btn btn-success gap-2" onclick="submitForm(\'#renovacionForm\', {
                        confirmMessage: \'¿Está seguro de que desea guardar la informacion?\',
                        onSuccess: async (response) => {
                            const renovacionId = response.reload?.data?.id;
                            
                            if (!renovacionId) return;

                            const result = await Swal.fire({
                                title: \'Renovación guardada\',
                                text: \'¿Desea imprimir el comprobante?\',
                                icon: \'success\',
                                showCancelButton: true,
                                confirmButtonText: \'Sí, imprimir\',
                                cancelButtonText: \'No, gracias\'
                            });

                            if (result.isConfirmed) {
                                try {
                                    await reporteManager.generarReporteDirect(
                                        \'seguros/comprobante-renovacion\',
                                        { 
                                            id: renovacionId,
                                            csrf_token: ';
			echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($csrf_token)) /* pos 411:57 */;
			echo '
                                        },
                                        { tipo: \'show\' }
                                    );
                                } catch (error) {
                                    console.error(\'Error generando comprobante:\', error);
                                }
                            }
                        }
                        });">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                    Guardar Renovación
                </button>
            </div>
        </div>
    </div>
';
		}
		echo '
    <dialog id="modal_cuentas" class="modal">
        <div class="modal-box w-11/12 max-w-5xl">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-lg font-bold">Buscar Cuenta</h3>
                <form method="dialog">
                    <button class="btn btn-sm btn-circle btn-ghost">✕</button>
                </form>
            </div>

            <div class="overflow-x-auto">
                <table class="table table-zebra table-sm w-full" id="cuentasTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Cliente</th>
                            <th>Identificación</th>
                            <th>Fecha Inicio</th>
                            <th>Estado</th>
                            <th class="text-center">Acción</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>

            <div class="modal-action">
                <form method="dialog">
                    <button class="btn btn-ghost">Cerrar</button>
                </form>
            </div>
        </div>

        <form method="dialog" class="modal-backdrop">
            <button>close</button>
        </form>
    </dialog>

    <script>
        $(document).ready(function() {
                startValidationGeneric(\'#renovacionForm\');
                
                const columns = [{
                        data: \'id\',
                        className: \'text-left\'
                    },
                    {
                        data: \'short_name\',
                        className: \'text-left\'
                    },
                    {
                        data: \'no_identifica\',
                    },
                    {
                        data: \'fecha_inicio\',
                        render: function(data, type, row) {
                            const date = new Date(data);
                            const day = String(date.getDate()).padStart(2, \'0\');
                            const month = String(date.getMonth() + 1).padStart(2, \'0\');
                            const year = date.getFullYear();
                            return `${day}/${month}/${year}`;
                        }
                    },
                    {
                        data: \'estado\',
                        render: function(data, type, row) {
                            let badgeClass = \'badge-info\';
                            const estado = data.toUpperCase();
                            if (estado === \'VIGENTE\') badgeClass = \'badge-success\';
                            if (estado === \'CERRADA\') badgeClass = \'badge-info\';
                            return `<span class="badge ${badgeClass} badge-sm">${estado}</span>`;
                        }
                    },
                    {
                        data: null,
                        title: \'Acción\',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row) {
                            return `<button class="btn btn-soft btn-success" onclick="loadModuleView(\'#cuadro\', {
                             route: \'api/seguros/renovaciones/${row.id}\'
                            });modal_cuentas.close();">Seleccionar</button>`;
                        }
                    }
                ];
                const table = initServerSideDataTable(
                    \'#cuentasTable\',
                    \'aux_cuentas\',
                    columns, {
                        onError: function(xhr, error, thrown) {
                            Swal.fire({
                                icon: \'error\',
                                title: \'Error al cargar clientes\',
                                text: \'Por favor, intente nuevamente\'
                            });
                        }
                    }
                );
            });
    </script>
</div>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['renovacion' => '157', 'cuentaBanco' => '336'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
