<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /var/www/html/app/Controllers/../../views/indicadores/seguros/beneficiarios.latte */
final class Template_0271388a6d extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="p-6 max-w-7xl mx-auto">
    <div class="card bg-gradient-to-br from-base-100 to-base-200 shadow-xl border border-base-300 mb-6">
        <div class="card-body">
            <div class="flex items-center justify-between mb-6">
                <div class="flex items-center gap-3">
                    <div>
                        <h2 class="card-title text-2xl">GESTION DE BENEFICIARIOS EN CUENTAS DE AUXILIO POSTUMO</h2>
                        <p class="text-sm text-base-content/60">
';
		if (isset($cuenta) && isset($cuenta->id)) /* pos 11:29 */ {
			echo '                            Cuenta #';
			echo LR\HtmlHelpers::escapeText($cuenta->id) /* pos 12:37 */;
			echo "\n";
		} else /* pos 13:29 */ {
			echo '                            Sin cuenta seleccionada
';
		}
		echo '                        </p>
                    </div>
                </div>
                <div class="flex gap-2">
                    <button type="button" class="btn btn-primary btn-sm gap-2" onclick="modal_cuentas.showModal()">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"></path>
                        </svg>
                        ';
		if (isset($cuenta) && isset($cuenta->id)) /* pos 26:25 */ {
			echo 'Cambiar';
		} else /* pos 26:73 */ {
			echo 'Seleccionar';
		}
		echo ' Cuenta
                    </button>
                    <button type="button" class="btn btn-ghost btn-sm" onclick="loadModuleView(\'#cuadro\', {
                                                route: \'api/seguros/beneficiarios/index\'
                                            });">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                        Cancelar
                    </button>
                </div>
            </div>

';
		if (!isset($cuenta) || !isset($cuenta->id)) /* pos 41:13 */ {
			echo '            <div class="alert alert-info shadow-lg">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    class="stroke-current shrink-0 w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <div>
                    <h3 class="font-bold">Ninguna cuenta seleccionada</h3>
                    <div class="text-xs">Use el botón "Seleccionar Cuenta" para buscar y elegir una cuenta.</div>
                </div>
            </div>
';
		} else /* pos 54:13 */ {
			echo '            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Cliente</div>
                    <div class="stat-value text-lg truncate"';
			echo LR\HtmlHelpers::formatAttribute(' title', $cuenta->cliente->short_name ?? 'N/A') /* pos 66:70 */;
			echo '>
                        ';
			echo LR\HtmlHelpers::escapeText($cuenta->cliente->short_name ?? 'N/A') /* pos 67:25 */;
			echo '
                    </div>
                    <div class="stat-desc">';
			echo LR\HtmlHelpers::escapeText($cuenta->cliente->no_identifica ?? '') /* pos 69:44 */;
			echo '</div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Servicio</div>
                    <div class="stat-value text-lg">';
			echo LR\HtmlHelpers::escapeText($cuenta->servicio->nombre ?? 'N/A') /* pos 81:53 */;
			echo '</div>
                    <div class="stat-desc">Costo: <span class="font-bold">';
			echo LR\HtmlHelpers::escapeText($cuenta->servicio->costo ?? 0) /* pos 82:75 */;
			echo '</span></div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-accent">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Fecha Inicio</div>
                    <div class="stat-value text-lg">
                        ';
			if (isset($cuenta->fecha_inicio)) /* pos 95:25 */ {
				echo LR\HtmlHelpers::escapeText(date('d/m/Y', strtotime($cuenta->fecha_inicio))) /* pos 95:58 */;
			} else /* pos 95:107 */ {
				echo 'N/A';
			}
			echo '
                    </div>
                    <div class="stat-desc">
';
			if (isset($cuenta->estado) && $cuenta->estado == 'vigente') /* pos 98:25 */ {
				echo '                        <span class="badge badge-success badge-sm">Vigente</span>
';
			} elseif (isset($cuenta->estado) && $cuenta->estado == 'cerrada') /* pos 100:25 */ {
				echo '                        <span class="badge badge-info badge-sm">Cerrada</span>
';
			} elseif (isset($cuenta->estado)) /* pos 102:25 */ {
				echo '                        <span class="badge badge-ghost badge-sm">';
				echo LR\HtmlHelpers::escapeText($cuenta->estado) /* pos 103:66 */;
				echo '</span>
';
			} else /* pos 104:25 */ {
				echo '                        <span class="badge badge-ghost badge-sm">Sin estado</span>
';
			}


			echo '                    </div>
                </div>
            </div>

';
			if (isset($cuenta->observaciones) && !empty($cuenta->observaciones)) /* pos 111:13 */ {
				echo '            <div class="mt-4 p-4 bg-base-200 rounded-lg">
                <div class="flex items-start gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-base-content/60 flex-shrink-0 mt-0.5"
                        fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path>
                    </svg>
                    <div>
                        <p class="text-xs font-semibold text-base-content/70 uppercase">Observaciones</p>
                        <p class="text-sm">';
				echo LR\HtmlHelpers::escapeText($cuenta->observaciones) /* pos 121:44 */;
				echo '</p>
                    </div>
                </div>
            </div>
';
			}
		}
		echo '        </div>
    </div>

';
		if (isset($cuenta) && isset($cuenta->id)) /* pos 131:5 */ {
			echo '    <div class="card bg-base-100 shadow-xl border border-base-300 mb-6">
        <div class="card-body">
            <div class="flex items-center justify-between mb-4">
                <div>
                    <h2 class="card-title text-xl">Beneficiarios Registrados</h2>
                    <p class="text-sm text-base-content/60">Lista de beneficiarios actuales de la cuenta</p>
                </div>
            </div>

';
			if (isset($cuenta->beneficiarios) && count($cuenta->beneficiarios) > 0) /* pos 142:13 */ {
				echo '            <div class="overflow-x-auto">
                <table class="table table-zebra table-sm w-full">
                    <thead>
                        <tr>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Identificación</th>
                            <th>Teléfono</th>
                            <th>Parentesco</th>
                            <th>Porcentaje</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
';
				foreach ($cuenta->beneficiarios as $beneficiario) /* pos 157:25 */ {
					echo '                        <tr>
                            <td>';
					echo LR\HtmlHelpers::escapeText($beneficiario->nombres) /* pos 159:33 */;
					echo '</td>
                            <td>';
					echo LR\HtmlHelpers::escapeText($beneficiario->apellidos) /* pos 160:33 */;
					echo '</td>
                            <td>';
					echo LR\HtmlHelpers::escapeText($beneficiario->identificacion) /* pos 161:33 */;
					echo '</td>
                            <td>';
					echo LR\HtmlHelpers::escapeText($beneficiario->telefono) /* pos 162:33 */;
					echo '</td>
                            <td>
                                <span class="badge badge-ghost badge-sm">
                                    ';
					echo LR\HtmlHelpers::escapeText($beneficiario->parentesco) /* pos 165:37 */;
					echo '
                                </span>
                            </td>
                            <td>
                                <span class="font-semibold">';
					echo LR\HtmlHelpers::escapeText($beneficiario->porcentaje) /* pos 169:61 */;
					echo '%</span>
                            </td>
                            <td class="text-center">
                                <div class="flex gap-1 justify-center">
                                    <button type="button" class="btn btn-ghost btn-xs" title="Editar"
                                        onclick="abrirModalEditar(';
					echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($beneficiario->id)) /* pos 174:67 */;
					echo ', ';
					echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($cuenta->id)) /* pos 174:88 */;
					echo ', ';
					echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($beneficiario->idParentesco)) /* pos 174:103 */;
					echo ', ';
					echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($beneficiario->porcentaje)) /* pos 174:134 */;
					echo ', \'';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->nombres) /* pos 174:164 */;
					echo '\', \'';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->apellidos) /* pos 174:201 */;
					echo '\', \'';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->identificacion) /* pos 174:240 */;
					echo '\', \'';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->telefono) /* pos 174:284 */;
					echo '\', \'';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->direccion) /* pos 174:322 */;
					echo '\')">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                            viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
                                        </svg>
                                    </button>
                                    <button type="button" class="btn btn-ghost btn-xs text-error" title="Eliminar"
                                        onclick="sendRequest({
                                            url: \'api/seguros/beneficiarios/';
					echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($beneficiario->idPivot)) /* pos 183:77 */;
					echo '\', 
                                            method: \'DELETE\', 
                                            confirmMessage: \'¿Está seguro de eliminar el beneficiario ';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->nombres) /* pos 185:105 */;
					echo ' ';
					echo LR\HtmlHelpers::escapeQuotes($beneficiario->apellidos) /* pos 185:139 */;
					echo '?\'
                                            });">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                            viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                        </svg>
                                    </button>
                                </div>
                            </td>
                        </tr>
';

				}

				echo '                    </tbody>
                    <tfoot>
                        <tr class="font-semibold">
                            <td colspan="5" class="text-right">Total Porcentaje:</td>
                            <td>
';
				$totalPorcentaje = $cuenta->beneficiarios->sum('porcentaje') /* pos 202:33 */;
				echo '                                <span
                                    class="text-lg ';
				if ($totalPorcentaje == 100) /* pos 204:52 */ {
					echo 'text-success';
				} elseif ($totalPorcentaje < 100) /* pos 204:92 */ {
					echo 'text-warning';
				} else /* pos 204:135 */ {
					echo 'text-error';
				}

				echo '">
                                    ';
				echo LR\HtmlHelpers::escapeText($totalPorcentaje) /* pos 205:37 */;
				echo '%
                                </span>
                            </td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
';
			} else /* pos 213:13 */ {
				echo '            <div class="alert alert-warning shadow-lg">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none"
                    viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path>
                </svg>
                <span>No hay beneficiarios registrados para esta cuenta.</span>
            </div>
';
			}
			echo '        </div>
    </div>

    <div class="card bg-base-100 shadow-xl border border-success/30 mb-6" id="beneficiariosForm"
        x-data="{ tipoAccion: \'nuevo\' }" data-action="api/seguros/beneficiarios" data-method="POST">
        <div class="card-body">
            <div class="flex items-center gap-3 mb-6">
                <div>
                    <h2 class="card-title text-2xl">Agregar Beneficiario</h2>
                    <p class="text-sm text-base-content/60">Seleccione un beneficiario existente o cree uno nuevo</p>
                </div>
            </div>

            <input type="hidden" name="csrf_token"';
			echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 237:60 */;
			echo '>
            <input type="hidden" name="id_cuenta"';
			echo LR\HtmlHelpers::formatAttribute(' value', $cuenta->id ?? '') /* pos 238:59 */;
			echo '>
            <input type="hidden" name="tipo_accion" x-model="tipoAccion">

            <div class="tabs tabs-boxed mb-6 bg-base-200 p-1 rounded-lg">
                <a class="tab tab-lg gap-2" :class="{ \'tab-active\': tipoAccion === \'nuevo\' }"
                    @click="tipoAccion = \'nuevo\'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                    </svg>
                    Crear Nuevo
                </a>
                <a class="tab tab-lg gap-2" :class="{ \'tab-active\': tipoAccion === \'existente\' }"
                    @click="tipoAccion = \'existente\'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                    </svg>
                    Seleccionar Existente
                </a>
            </div>

            <div x-show="tipoAccion === \'existente\'" x-cloak>
                <div class="alert alert-info mb-4">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        class="stroke-current shrink-0 w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    <span>Busque y seleccione un beneficiario ya registrado en el sistema</span>
                </div>

                <div class="form-control mb-4">
                    <label class="label">
                        <span class="label-text font-semibold">Beneficiario</span>
                    </label>
                    <button type="button" class="btn btn-outline btn-primary gap-2"
                        onclick="modal_beneficiarios_existentes.showModal()">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                        Buscar Beneficiario
                    </button>
                    <input type="hidden" id="id_beneficiario_existente" name="id_beneficiario_existente"
                        :required="tipoAccion === \'existente\'" data-label="Beneficiario Existente" />
                </div>

                <div id="beneficiario_seleccionado_info" style="display: none;" class="bg-base-200 rounded-lg p-4 mb-4">
                    <h3 class="font-bold text-lg mb-3">Beneficiario Seleccionado</h3>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
                        <div>
                            <p class="text-xs text-base-content/60">Nombre Completo</p>
                            <p class="font-semibold" id="info_nombre"></p>
                        </div>
                        <div>
                            <p class="text-xs text-base-content/60">Identificación</p>
                            <p class="font-semibold" id="info_identificacion"></p>
                        </div>
                        <div>
                            <p class="text-xs text-base-content/60">Teléfono</p>
                            <p class="font-semibold" id="info_telefono"></p>
                        </div>
                        <div>
                            <p class="text-xs text-base-content/60">Dirección</p>
                            <p class="font-semibold" id="info_direccion"></p>
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                                </svg>
                                Parentesco
                            </span>
                        </label>
                        <select class="select select-bordered select-primary" id="parentesco_existente"
                            :required="tipoAccion === \'existente\'" name="parentesco_existente" data-label="Parentesco">
                            <option value="">Seleccione parentesco</option>
';
			if (isset($parentescos)) /* pos 327:29 */ {
				foreach ($parentescos as $p) /* pos 328:29 */ {
					echo '                            <option';
					echo LR\HtmlHelpers::formatAttribute(' value', $p->id) /* pos 329:45 */;
					echo '>';
					echo LR\HtmlHelpers::escapeText($p->descripcion) /* pos 329:54 */;
					echo '</option>
';

				}

			}
			echo '                        </select>
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path>
                                </svg>
                                Porcentaje (%)
                            </span>
                        </label>
                        <input type="number" step="0.01" id="porcentaje_existente" name="porcentaje_existente"
                            class="input input-bordered input-primary" placeholder="Ej: 50.00" min="0.01" max="100"
                            :required="tipoAccion === \'existente\'" data-label="Porcentaje" />
                    </div>
                </div>
            </div>

            <div x-show="tipoAccion === \'nuevo\'" x-cloak>
                <div class="alert alert-success mb-4">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        class="stroke-current shrink-0 w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    <span>Complete los datos para registrar un nuevo beneficiario en el sistema</span>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                                </svg>
                                Nombres
                            </span>
                        </label>
                        <input :required="tipoAccion === \'nuevo\'" type="text" id="nombres" name="nombres"
                            class="input input-bordered input-primary" placeholder="Ej: Juan Carlos"
                            data-label="Nombres" />
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                                </svg>
                                Apellidos
                            </span>
                        </label>
                        <input :required="tipoAccion === \'nuevo\'" type="text" id="apellidos" name="apellidos"
                            class="input input-bordered input-primary" placeholder="Ej: Pérez García"
                            data-label="Apellidos" />
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                                </svg>
                                Identificación
                            </span>
                        </label>
                        <input :required="tipoAccion === \'nuevo\'" type="text" id="identificacion" name="identificacion"
                            class="input input-bordered input-primary" placeholder="Ej: 1011010121213"
                            data-label="Identificación" />
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path>
                                </svg>
                                Teléfono
                            </span>
                        </label>
                        <input :required="tipoAccion === \'nuevo\'" type="text" id="telefono" name="telefono"
                            class="input input-bordered input-primary" placeholder="Ej: 88888888"
                            data-label="Teléfono" />
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                </svg>
                                Dirección
                            </span>
                        </label>
                        <input :required="tipoAccion === \'nuevo\'" type="text" id="direccion" name="direccion"
                            class="input input-bordered input-primary" placeholder="Ej: Barrio XXX, de la XXX 1c al sur"
                            data-label="Dirección" />
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                                </svg>
                                Parentesco
                            </span>
                        </label>
                        <select class="select select-bordered select-primary" id="parentesco" name="parentesco"
                            :required="tipoAccion === \'nuevo\'" data-label="Parentesco">
                            <option value="" disabled selected>Seleccione</option>
';
			if (isset($parentescos)) /* pos 461:29 */ {
				foreach ($parentescos as $parentesco) /* pos 462:29 */ {
					echo '                            <option';
					echo LR\HtmlHelpers::formatAttribute(' value', $parentesco->id) /* pos 463:45 */;
					echo '>';
					echo LR\HtmlHelpers::escapeText($parentesco->descripcion) /* pos 463:63 */;
					echo '</option>
';

				}

			}
			echo '                        </select>
                    </div>

                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                                </svg>
                                Porcentaje (%)
                            </span>
                        </label>
                        <input type="number" step="0.01" id="porcentaje" name="porcentaje"
                            class="input input-bordered input-primary" placeholder="Ej: 50.00"
                            :required="tipoAccion === \'nuevo\'" data-label="Porcentaje" min="0" max="100" />
                    </div>
                </div>
            </div>


            <div class="divider"></div>

            <div class="flex gap-3 justify-end">
                <button type="button" class="btn btn-ghost gap-2" onclick="loadModuleView(\'#cuadro\', {
                                                route: \'api/seguros/beneficiarios/index\'
                                            });">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                    Cancelar
                </button>
                <button type="button" class="btn btn-success gap-2" onclick="submitForm(\'#beneficiariosForm\', {
                        confirmMessage: \'¿Está seguro de que desea guardar el beneficiario?\',
                        });">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                    Guardar Beneficiario
                </button>
            </div>
        </div>
    </div>
';
		}
		echo '
    <dialog id="modal_cuentas" class="modal">
        <div class="modal-box w-11/12 max-w-5xl">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-lg font-bold">Buscar Cuenta</h3>
                <form method="dialog">
                    <button class="btn btn-sm btn-circle btn-ghost">✕</button>
                </form>
            </div>

            <div class="overflow-x-auto">
                <table class="table table-zebra table-sm w-full" id="cuentasTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Cliente</th>
                            <th>Identificación</th>
                            <th>Fecha Inicio</th>
                            <th>Estado</th>
                            <th class="text-center">Acción</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>

            <div class="modal-action">
                <form method="dialog">
                    <button class="btn btn-ghost">Cerrar</button>
                </form>
            </div>
        </div>

        <form method="dialog" class="modal-backdrop">
            <button>close</button>
        </form>
    </dialog>

    <dialog id="modal_beneficiarios_existentes" class="modal">
        <div class="modal-box w-11/12 max-w-5xl">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-lg font-bold">Seleccionar Beneficiario</h3>
                <form method="dialog">
                    <button class="btn btn-sm btn-circle btn-ghost">✕</button>
                </form>
            </div>

            <div class="overflow-x-auto">
                <table class="table table-zebra table-sm w-full" id="beneficiariosTable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Identificación</th>
                            <th>Teléfono</th>
                            <th class="text-center">Acción</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>

            <div class="modal-action">
                <form method="dialog">
                    <button class="btn btn-ghost">Cerrar</button>
                </form>
            </div>
        </div>

        <form method="dialog" class="modal-backdrop">
            <button>close</button>
        </form>
    </dialog>

    <input type="checkbox" style="display: none" id="modal_editar_beneficiario" class="modal-toggle" />
    <div class="modal" role="dialog">
        <div class="modal-box max-w-3xl">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-lg font-bold">Editar Beneficiario</h3>
                <label for="modal_editar_beneficiario" class="btn btn-sm btn-circle btn-ghost">✕</label>
            </div>

            <div role="tablist" class="tabs tabs-bordered mb-4">
                <input type="radio" name="edit_tabs" role="tab" class="tab" aria-label="Relación con Cuenta" checked />
                <div role="tabpanel" class="tab-content p-4">
                    <div id="editarRelacionForm" data-action="api/seguros/beneficiarios" data-method="PUT">
                        <input type="hidden" name="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 611:72 */;
		echo '>
                        <input type="hidden" id="edit_rel_id_beneficiario" name="id_beneficiario">
                        <input type="hidden" id="edit_rel_id_cuenta" name="id_cuenta">
                        <input type="hidden" name="tipo_edicion" value="relacion">

                        <div class="mb-4">
                            <label class="label">
                                <span class="label-text font-semibold">Beneficiario</span>
                            </label>
                            <input type="text" id="edit_rel_nombre_beneficiario" class="input input-bordered w-full"
                                disabled>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text font-semibold">Parentesco</span>
                                </label>
                                <select class="select select-bordered select-primary" id="edit_rel_parentesco"
                                    name="parentesco" required data-label="Parentesco">
                                    <option value="">Seleccione</option>
';
		if (isset($parentescos)) /* pos 632:37 */ {
			foreach ($parentescos as $p) /* pos 633:37 */ {
				echo '                                    <option';
				echo LR\HtmlHelpers::formatAttribute(' value', $p->id) /* pos 634:53 */;
				echo '>';
				echo LR\HtmlHelpers::escapeText($p->descripcion) /* pos 634:62 */;
				echo '</option>
';

			}

		}
		echo '                                </select>
                            </div>

                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text font-semibold">Porcentaje (%)</span>
                                </label>
                                <input type="number" step="0.01" id="edit_rel_porcentaje" name="porcentaje"
                                    class="input input-bordered input-primary" placeholder="Ej: 50.00" required
                                    min="0.01" max="100" data-label="Porcentaje" />
                            </div>
                        </div>

                        <div class="modal-action">
                            <label for="modal_editar_beneficiario" class="btn btn-ghost">Cancelar</label>
                            <button type="button" class="btn btn-primary" onclick="submitForm(\'#editarRelacionForm\', {
                                confirmMessage: \'¿Está seguro de actualizar la relación de este beneficiario?\'
                            })">
                                Guardar Relación
                            </button>
                        </div>
                    </div>
                </div>

                <input type="radio" name="edit_tabs" role="tab" class="tab" aria-label="Datos Personales" />
                <div role="tabpanel" class="tab-content p-4">
                    <div id="editarDatosForm" data-action="api/seguros/beneficiarios" data-method="PUT">
                        <input type="hidden" name="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 665:72 */;
		echo '>
                        <input type="hidden" id="edit_datos_id_beneficiario" name="id_beneficiario">
                        <input type="hidden" name="tipo_edicion" value="datos">

                        <div class="space-y-4">
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div class="form-control">
                                    <label class="label">
                                        <span class="label-text font-semibold">Nombres</span>
                                    </label>
                                    <input type="text" id="edit_datos_nombres" name="nombres"
                                        class="input input-bordered input-primary" placeholder="Nombres" required
                                        maxlength="100" data-label="Nombres" />
                                </div>

                                <div class="form-control">
                                    <label class="label">
                                        <span class="label-text font-semibold">Apellidos</span>
                                    </label>
                                    <input type="text" id="edit_datos_apellidos" name="apellidos"
                                        class="input input-bordered input-primary" placeholder="Apellidos" required
                                        maxlength="100" data-label="Apellidos" />
                                </div>
                            </div>

                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div class="form-control">
                                    <label class="label">
                                        <span class="label-text font-semibold">Identificación</span>
                                    </label>
                                    <input type="text" id="edit_datos_identificacion" name="identificacion"
                                        class="input input-bordered input-primary" placeholder="Cédula o RUC" required
                                        maxlength="20" data-label="Identificación" />
                                </div>

                                <div class="form-control">
                                    <label class="label">
                                        <span class="label-text font-semibold">Teléfono</span>
                                    </label>
                                    <input type="text" id="edit_datos_telefono" name="telefono"
                                        class="input input-bordered input-primary" placeholder="Teléfono" required
                                        maxlength="20" data-label="Teléfono" />
                                </div>
                            </div>

                            <div class="form-control">
                                <label class="label">
                                    <span class="label-text font-semibold">Dirección</span>
                                </label>
                                <input type="text" id="edit_datos_direccion" name="direccion"
                                    class="input input-bordered input-primary" placeholder="Dirección completa" required
                                    maxlength="255" data-label="Dirección" />
                            </div>
                        </div>

                        <div class="modal-action">
                            <label for="modal_editar_beneficiario" class="btn btn-ghost">Cancelar</label>
                            <button type="button" class="btn btn-primary" onclick="submitForm(\'#editarDatosForm\', {
                                confirmMessage: \'¿Está seguro de actualizar los datos de este beneficiario?\'
                            })">
                                Guardar Datos
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <label class="modal-backdrop" for="modal_editar_beneficiario">Cerrar</label>
    </div>

    <script>
        $(document).ready(function() {
                startValidationGeneric(\'#beneficiariosForm\');
                startValidationGeneric(\'#editarRelacionForm\');
                startValidationGeneric(\'#editarDatosForm\');
                
                // DataTable para Cuentas
                const columns = [{
                        data: \'id\',
                        className: \'text-left\'
                    },
                    {
                        data: \'short_name\',
                        className: \'text-left\'
                    },
                    {
                        data: \'no_identifica\',
                    },
                    {
                        data: \'fecha_inicio\',
                        render: function(data, type, row) {
                            const date = new Date(data);
                            const day = String(date.getDate()).padStart(2, \'0\');
                            const month = String(date.getMonth() + 1).padStart(2, \'0\');
                            const year = date.getFullYear();
                            return `${day}/${month}/${year}`;
                        }
                    },
                    {
                        data: \'estado\',
                        render: function(data, type, row) {
                            let badgeClass = \'badge-info\';
                            const estado = data.toUpperCase();
                            if (estado === \'VIGENTE\') badgeClass = \'badge-success\';
                            if (estado === \'CERRADA\') badgeClass = \'badge-info\';
                            return `<span class="badge ${badgeClass} badge-sm">${estado}</span>`;
                        }
                    },
                    {
                        data: null,
                        title: \'Acción\',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row) {
                            return `<button class="btn btn-soft btn-success" onclick="loadModuleView(\'#cuadro\', {
                             route: \'api/seguros/beneficiarios/${row.id}\'
                            });modal_cuentas.close();">Seleccionar</button>`;
                        }
                    }
                ];
                const table = initServerSideDataTable(
                    \'#cuentasTable\',
                    \'aux_cuentas\',
                    columns, {
                        onError: function(xhr, error, thrown) {
                            Swal.fire({
                                icon: \'error\',
                                title: \'Error al cargar clientes\',
                                text: \'Por favor, intente nuevamente\'
                            });
                        }
                    }
                );

                // DataTable para Beneficiarios Existentes
                const beneficiariosColumns = [
                    {
                        data: \'id\',
                        className: \'text-left\'
                    },
                    {
                        data: \'nombres\',
                        className: \'text-left\'
                    },
                    {
                        data: \'apellidos\',
                        className: \'text-left\'
                    },
                    {
                        data: \'identificacion\',
                        className: \'text-left\'
                    },
                    {
                        data: \'telefono\',
                        className: \'text-left\'
                    },
                    {
                        data: null,
                        title: \'Acción\',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row) {
                            return `<button class="btn btn-soft btn-success btn-sm" onclick="seleccionarBeneficiario(${row.id}, \'${row.nombres}\', \'${row.apellidos}\', \'${row.identificacion}\', \'${row.telefono}\', \'${row.direccion}\')">Seleccionar</button>`;
                        }
                    }
                ];

                const beneficiariosTable = initServerSideDataTable(
                    \'#beneficiariosTable\',
                    \'cli_beneficiarios\',
                    beneficiariosColumns,
                    {
                        onError: function(xhr, error, thrown) {
                            Swal.fire({
                                icon: \'error\',
                                title: \'Error al cargar beneficiarios\',
                                text: \'Por favor, intente nuevamente\'
                            });
                        }
                    }
                );
            });

        // Función para abrir modal de edición
        function abrirModalEditar(idBeneficiario, idCuenta, parentesco, porcentaje, nombres, apellidos, identificacion, telefono, direccion) {
            // Tab 1: Relación con cuenta
            $(\'#edit_rel_id_beneficiario\').val(idBeneficiario);
            $(\'#edit_rel_id_cuenta\').val(idCuenta);
            $(\'#edit_rel_nombre_beneficiario\').val(nombres + \' \' + apellidos);
            $(\'#edit_rel_parentesco\').val(parentesco);
            $(\'#edit_rel_porcentaje\').val(porcentaje);
            
            // Tab 2: Datos personales
            $(\'#edit_datos_id_beneficiario\').val(idBeneficiario);
            $(\'#edit_datos_nombres\').val(nombres);
            $(\'#edit_datos_apellidos\').val(apellidos);
            $(\'#edit_datos_identificacion\').val(identificacion);
            $(\'#edit_datos_telefono\').val(telefono);
            $(\'#edit_datos_direccion\').val(direccion);
            
            // Abrir modal
            $(\'#modal_editar_beneficiario\').prop(\'checked\', true);
        }

        // Función para seleccionar beneficiario existente
        function seleccionarBeneficiario(id, nombres, apellidos, identificacion, telefono, direccion) {
            // Guardar el ID
            $(\'#id_beneficiario_existente\').val(id);
            
            // Mostrar información del beneficiario seleccionado
            $(\'#info_nombre\').text(nombres + \' \' + apellidos);
            $(\'#info_identificacion\').text(identificacion);
            $(\'#info_telefono\').text(telefono);
            $(\'#info_direccion\').text(direccion);
            
            // Mostrar el panel de información
            $(\'#beneficiario_seleccionado_info\').slideDown();
            
            // Cerrar el modal
            modal_beneficiarios_existentes.close();
        }
    </script>
</div>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['beneficiario' => '157', 'p' => '328, 633', 'parentesco' => '462'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
