<?php

/** Generated by Latte 3.1.0 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /var/www/html/app/Controllers/../../views/indicadores/seguros/cuentas.latte */
final class Template_0511dccf11 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="p-6 max-w-6xl mx-auto">
    <div class="card bg-gradient-to-br from-base-100 to-base-200 shadow-xl border border-base-300 mb-6">
        <div class="card-body">
            <div class="flex items-center justify-between mb-6">
                <div class="flex items-center gap-3">
                    <div class="avatar placeholder">
                        <div class="bg-primary text-primary-content rounded-full w-12">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                            </svg>
                        </div>
                    </div>
                    <div>
                        <h2 class="card-title text-2xl">Información del Cliente</h2>
                        <p class="text-sm text-base-content/60">Datos del asociado seleccionado</p>
                    </div>
                </div>
                <button type="button" class="btn btn-primary btn-sm gap-2" onclick="my_modal_1.showModal()">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                    Cambiar Cliente
                </button>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Código Cliente</div>
                    <div id="cliente_codigo_display" class="stat-value text-xl text-primary">
                        ';
		echo LR\HtmlHelpers::escapeText($currentClient['idcod_cliente'] ?? 'N/A') /* pos 47:25 */;
		echo '
                    </div>
                    <div class="stat-desc">Identificador único</div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Nombre Completo</div>
                    <div id="cliente_nombre_display" class="stat-value text-xl truncate"';
		echo LR\HtmlHelpers::formatAttribute('
                        title', $currentClient['short_name'] ?? 'Sin seleccionar') /* pos 63:33 */;
		echo '>
                        ';
		echo LR\HtmlHelpers::escapeText($currentClient['short_name'] ?? 'Sin seleccionar') /* pos 64:25 */;
		echo '
                    </div>
                    <div class="stat-desc">Nombre del asociado</div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-accent">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M10 6H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V8a2 2 0 00-2-2h-5m-4 0V5a2 2 0 114 0v1m-4 0a2 2 0 104 0m-5 8a2 2 0 100-4 2 2 0 000 4zm0 0c1.306 0 2.417.835 2.83 2M9 14a3.001 3.001 0 00-2.83 2M15 11h3m-3 4h2"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Identificación</div>
                    <div id="cliente_identificacion_display" class="stat-value text-xl">
                        ';
		echo LR\HtmlHelpers::escapeText($currentClient['no_identifica'] ?? 'N/A') /* pos 80:25 */;
		echo '
                    </div>
                    <div class="stat-desc">Documento de identidad</div>
                </div>

                <div class="stat bg-base-100 rounded-lg shadow-sm border border-base-300">
                    <div class="stat-figure text-success">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                    </div>
                    <div class="stat-title text-xs font-semibold uppercase tracking-wide">Estado</div>
                    <div class="stat-value text-xl">
';
		if (isset($currentClient['idcod_cliente'])) /* pos 96:25 */ {
			echo '                        <span class="badge badge-success badge-lg">Activo</span>
';
		} else /* pos 98:25 */ {
			echo '                        <span class="badge badge-ghost badge-lg">Pendiente</span>
';
		}
		echo '                    </div>
                    <div class="stat-desc">
';
		if (isset($currentClient['idcod_cliente'])) /* pos 103:25 */ {
			echo '                        Cliente seleccionado
';
		} else /* pos 105:25 */ {
			echo '                        Seleccione un cliente
';
		}
		echo '                    </div>
                </div>
            </div>

';
		if (!isset($currentClient['idcod_cliente'])) /* pos 113:13 */ {
			echo '            <div class="alert alert-info shadow-lg mt-6">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    class="stroke-current shrink-0 w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <div>
                    <h3 class="font-bold">Ningún cliente seleccionado</h3>
                    <div class="text-xs">Use el botón "Cambiar Cliente" para buscar y seleccionar un asociado.</div>
                </div>
            </div>
';
		}
		echo '        </div>
    </div>

';
		if (isset($cuentas) && count($cuentas) > 0) /* pos 130:5 */ {
			echo '    <div class="card bg-base-100 shadow-xl border border-base-300 mb-6">
        <div class="card-body">
            <div class="flex items-center justify-between mb-6">
                <div class="flex items-center gap-3">
                    <div>
                        <h2 class="card-title text-2xl">Cuentas del Cliente</h2>
                        <p class="text-sm text-base-content/60">Servicios contratados actualmente</p>
                    </div>
                </div>
                <div class="badge badge-accent badge-lg gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    ';
			echo LR\HtmlHelpers::escapeText(count($cuentas)) /* pos 147:21 */;
			echo ' ';
			echo LR\HtmlHelpers::escapeText(count($cuentas) == 1 ? 'Cuenta' : 'Cuentas') /* pos 147:39 */;
			echo '
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
';
			foreach ($cuentas as $cuenta) /* pos 153:17 */ {
				echo '                <div
                    class="card bg-gradient-to-br from-base-200 to-base-300 shadow-lg hover:shadow-xl transition-all duration-200 border border-base-300">
                    <div class="card-body p-5">
                        <div class="flex items-start justify-between mb-3">
                            <div class="flex items-center gap-2">
                                <div class="badge badge-neutral badge-sm"># ';
				echo LR\HtmlHelpers::escapeText($cuenta['id']) /* pos 160:77 */;
				echo '</div>
                            </div>
                            <div>
';
				if ($cuenta['estado'] == 'vigente') /* pos 163:33 */ {
					echo '                                <span class="badge badge-success gap-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M5 13l4 4L19 7"></path>
                                    </svg>
                                    Vigente
                                </span>
';
				} else /* pos 172:33 */ {
					echo '                                <span class="badge badge-error gap-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M6 18L18 6M6 6l12 12"></path>
                                    </svg>
                                    Inactiva
                                </span>
';
				}
				echo '                            </div>
                        </div>

                        <h3 class="font-bold text-lg mb-3 text-base-content">
                            ';
				echo LR\HtmlHelpers::escapeText($cuenta['servicio_nombre']) /* pos 187:29 */;
				echo '
                        </h3>

                        <div class="space-y-2">
                            <div class="flex items-center justify-between py-2 border-b border-base-content/10">
                                <span class="text-sm text-base-content/70 flex items-center gap-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                    </svg>
                                    Costo
                                </span>
                                <span class="font-bold text-primary text-lg">';
				echo LR\HtmlHelpers::escapeText($cuenta['servicio_costo']) /* pos 202:78 */;
				echo '</span>
                            </div>

                            <div class="flex items-center justify-between py-2 border-b border-base-content/10">
                                <span class="text-sm text-base-content/70 flex items-center gap-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                                    </svg>
                                    Inicio
                                </span>
                                <span class="font-semibold">';
				echo LR\HtmlHelpers::escapeText(date('d/m/Y', strtotime($cuenta['fecha_inicio']))) /* pos 215:61 */;
				echo '</span>
                            </div>

';
				if (!empty($cuenta['observaciones'])) /* pos 219:29 */ {
					echo '                            <div class="pt-2">
                                <p class="text-xs text-base-content/60 italic line-clamp-2"';
					echo LR\HtmlHelpers::formatAttribute('
                                    title', $cuenta['observaciones']) /* pos 222:45 */;
					echo '>
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3 inline mr-1" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path>
                                    </svg>
                                    ';
					echo LR\HtmlHelpers::escapeText($cuenta['observaciones']) /* pos 228:37 */;
					echo '
                                </p>
                            </div>
';
				}
				echo '                        </div>

                    </div>
                </div>
';

			}

			echo '            </div>
        </div>
    </div>
';
		}
		echo '
    <div class="grid grid-cols-1 lg:grid-cols-1 gap-6 mt-6" id="formCuenta" data-action="api/seguros/cuentas"
        data-method="POST">
        <input type="hidden" name="csrf_token" id="csrf_token"';
		echo LR\HtmlHelpers::formatAttribute(' value', $csrf_token) /* pos 265:72 */;
		echo '>
        <input type="hidden" name="id_cliente" id="id_cliente"';
		echo LR\HtmlHelpers::formatAttribute(' value', $currentClient['idcod_cliente'] ?? '') /* pos 266:72 */;
		echo '>

        <div class="card bg-base-100 shadow-xl">
            <div class="card-body">
                <div class="flex items-center justify-between mb-6">
                    <h2 class="card-title text-2xl">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                        </svg>
                        Información del Servicio
                    </h2>
                </div>

                <div class="form-control mb-6">
                    <label class="label">
                        <span class="label-text font-semibold text-lg">Seleccione un Servicio</span>
                        <span class="label-text-alt text-error">*Requerido</span>
                    </label>

                    <div id="servicios-grid"
                        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 max-h-96 overflow-y-auto p-2">
';
		foreach ($services as $service) /* pos 291:25 */ {
			echo '                        <div class="service-card card bg-base-200 hover:bg-base-300 cursor-pointer transition-all duration-200 border-2 border-transparent hover:border-primary hover:shadow-lg"';
			echo LR\HtmlHelpers::formatDataAttribute('
                            data-service-id', $service['id']) /* pos 293:47 */;
			echo LR\HtmlHelpers::formatDataAttribute(' data-service-nombre', $service['nombre']) /* pos 293:86 */;
			echo LR\HtmlHelpers::formatDataAttribute('
                            data-service-costo', $service['costo']) /* pos 294:50 */;
			echo ' onclick="selectService(this)">
                            <div class="card-body p-4">
                                <div class="flex items-start justify-between">
                                    <div class="flex-1">
                                        <h3 class="card-title text-base font-bold mb-2">';
			echo LR\HtmlHelpers::escapeText($service['nombre']) /* pos 298:89 */;
			echo '</h3>
                                        <p class="text-sm text-base-content/70 mb-3 line-clamp-2">
                                            ';
			echo LR\HtmlHelpers::escapeText($service['descripcion']) /* pos 300:45 */;
			echo '</p>
                                    </div>
                                    <div class="form-control">
                                        <input type="radio" name="servicio_id"';
			echo LR\HtmlHelpers::formatAttribute(' value', $service['id']) /* pos 303:88 */;
			echo '
                                            class="radio radio-primary radio-sm" />
                                    </div>
                                </div>
                                <div class="badge badge-primary badge-lg font-semibold">
                                    ';
			echo LR\HtmlHelpers::escapeText($service['costo']) /* pos 308:37 */;
			echo '
                                </div>
                            </div>
                        </div>
';

		}

		echo '                    </div>
                    <input type="hidden" id="selected_service_id" name="selected_service_id" data-label="servicios"
                        required>
                </div>

                <div class="divider"></div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div class="form-control">
                        <label class="label">
                            <span class="label-text font-semibold flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                                </svg>
                                Fecha de Inicio
                            </span>
                            <span class="label-text-alt text-error">*Requerido</span>
                        </label>
                        <div class="relative">
                            <input type="date" name="fecha_inicio" id="fecha_inicio"
                                class="input input-bordered input-primary w-full font-medium"';
		echo LR\HtmlHelpers::formatAttribute(' value', date('Y-m-d')) /* pos 337:103 */;
		echo '
                                required />
                            <div class="absolute inset-y-0 right-3 flex items-center pointer-events-none">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-primary" fill="none"
                                    viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                                </svg>
                            </div>
                        </div>
                        <label class="label">
                            <span class="label-text-alt">Seleccione la fecha de inicio del servicio</span>
                        </label>
                    </div>

                    <div id="service-summary" class="card bg-primary/10 border-2 border-primary/30 hidden">
                        <div class="card-body p-4">
                            <h4 class="font-bold text-sm text-primary mb-2">Servicio Seleccionado</h4>
                            <p id="summary-nombre" class="font-semibold text-base mb-1"></p>
                            <p id="summary-costo" class="text-2xl font-bold text-primary"></p>
                        </div>
                    </div>
                </div>

                <div class="form-control mt-4">
                    <label class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
                            </svg>
                            Observaciones
                        </span>
                        <span class="label-text-alt">Opcional</span>
                    </label>
                    <textarea name="observaciones" id="observaciones" rows="4" maxlength="255"
                        class="textarea textarea-bordered textarea-primary w-full resize-none focus:textarea-accent"
                        placeholder="Ingrese cualquier observación o nota adicional sobre el servicio..."></textarea>
                </div>

                <div class="divider"></div>

                <div class="flex gap-3 justify-end">
                    <button type="button" class="btn btn-ghost gap-2" onclick="loadModuleView(\'#cuadro\', {
                                                route: \'api/seguros/cuentas/index\'
                                            });">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                        Cancelar
                    </button>
';
		if (isset($currentClient['idcod_cliente'])) /* pos 398:21 */ {
			echo '                    <button type="button" class="btn btn-primary gap-2" onclick="submitForm(\'#formCuenta\', {
                        confirmMessage: \'¿Está seguro de que desea guardar la informacion?\'
                        });">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                        </svg>
                        Guardar Servicio
                    </button>
';
		}
		echo '                </div>
            </div>
        </div>
    </div>
    <dialog id="my_modal_1" class="modal">
        <div class="modal-box w-11/12 max-w-5xl">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-lg font-bold">Buscar Cliente</h3>
                <form method="dialog">
                    <button class="btn btn-sm btn-circle btn-ghost">✕</button>
                </form>
            </div>
            <div class="overflow-x-auto">
                <table id="clientesTable" class="table table-zebra table-sm w-full">
                    <thead>
                        <tr>
                            <th>Código</th>
                            <th>Nombre</th>
                            <th>Identificación</th>
                            <th class="text-center">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>

            <div class="modal-action">
                <form method="dialog">
                    <button class="btn btn-ghost">Cerrar</button>
                </form>
            </div>
        </div>

        <form method="dialog" class="modal-backdrop">
            <button>close</button>
        </form>
    </dialog>

    <script>
        // Función para seleccionar servicio
        function selectService(card) {
            // Remover selección previa
            document.querySelectorAll(\'.service-card\').forEach(c => {
                c.classList.remove(\'border-primary\', \'bg-primary/10\', \'shadow-lg\');
                c.classList.add(\'border-transparent\');
            });
            
            // Marcar como seleccionado
            card.classList.add(\'border-primary\', \'bg-primary/10\', \'shadow-lg\');
            card.classList.remove(\'border-transparent\');
            
            // Marcar el radio
            const radio = card.querySelector(\'input[type="radio"]\');
            radio.checked = true;
            
            // Guardar en input hidden
            const serviceId = card.dataset.serviceId;
            const serviceNombre = card.dataset.serviceNombre;
            const serviceCosto = card.dataset.serviceCosto;
            
            document.getElementById(\'selected_service_id\').value = serviceId;
            
            // Mostrar resumen
            const summary = document.getElementById(\'service-summary\');
            summary.classList.remove(\'hidden\');
            document.getElementById(\'summary-nombre\').textContent = serviceNombre;
            document.getElementById(\'summary-costo\').textContent = \'\' + parseFloat(serviceCosto).toFixed(2);
        }

        $(document).ready(function() {

                // DataTable de clientes
                const columns = [{
                        data: \'codigo_cliente\',
                        className: \'text-left\'
                    },
                    {
                        data: \'nombre\',
                        className: \'text-left\'
                    },
                    {
                        data: \'identificacion\',
                    },
                    {
                        data: null,
                        title: \'Acción\',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row) {
                            return `<button class="btn btn-soft btn-success" onclick="loadModuleView(\'#cuadro\', {
                             route: \'api/seguros/cuentas/edit/${row.codigo_cliente}\'
                            });
                            my_modal_1.close();">
                            Seleccionar</button>`;
                        }
                    }
                ];
                
                const table = initServerSideDataTable(
                    \'#clientesTable\',
                    \'cli_clientes_all\',
                    columns, {
                        onError: function(xhr, error, thrown) {
                            Swal.fire({
                                icon: \'error\',
                                title: \'Error al cargar clientes\',
                                text: \'Por favor, intente nuevamente\'
                            });
                        }
                    }
                );
            });
    </script>
</div>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['cuenta' => '153', 'service' => '291'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
